//! Versioned native C ABI vocabulary for PLRI operations.

mod symbol;
mod version;

pub use symbol::{
    ACTOR_ACTIVATE_SYMBOL, ACTOR_BEGIN_EXIT_SYMBOL, ACTOR_COMPLETE_EXIT_SYMBOL,
    ACTOR_CREATE_SYMBOL, ACTOR_RELEASE_SYMBOL, ACTOR_TRY_RECEIVE_SYMBOL, ACTOR_TRY_SEND_SYMBOL,
    ALLOCATE_INITIALIZED_OBJECT_AT_SITE_AND_STORE_ARRAY_SYMBOL,
    ALLOCATE_INITIALIZED_SELF_REFERENTIAL_OBJECT_AT_SITE_SYMBOL,
    ARRAY_GET_OBJECT_FIELD_CHECKED_SYMBOL, ATOMIC_BOOL_COMPARE_EXCHANGE_SYMBOL,
    ATOMIC_BOOL_CREATE_SYMBOL, ATOMIC_BOOL_LOAD_SYMBOL, ATOMIC_BOOL_STORE_SYMBOL,
    ATOMIC_BOOL_SWAP_SYMBOL, ATOMIC_INT_COMPARE_EXCHANGE_SYMBOL, ATOMIC_INT_CREATE_SYMBOL,
    ATOMIC_INT_FETCH_ADD_SYMBOL, ATOMIC_INT_FETCH_AND_SYMBOL, ATOMIC_INT_FETCH_OR_SYMBOL,
    ATOMIC_INT_FETCH_SUBTRACT_SYMBOL, ATOMIC_INT_FETCH_XOR_SYMBOL, ATOMIC_INT_LOAD_SYMBOL,
    ATOMIC_INT_STORE_SYMBOL, ATOMIC_INT_SWAP_SYMBOL, ATOMIC_RELEASE_SYMBOL, DEADLINE_AFTER_SYMBOL,
    DEADLINE_CLOSE_SYMBOL, DEADLINE_EXPIRED_SYMBOL, ITERATION_MAKE_SYMBOL,
    MONOTONIC_CLOCK_CLOSE_SYMBOL, MONOTONIC_CLOCK_CREATE_SYMBOL, MONOTONIC_CLOCK_NOW_SYMBOL,
    TABLE_GET_CHECKED_SYMBOL, TCP_ACCEPT_SYMBOL, TCP_CLOSE_SYMBOL, TCP_CONNECT_IPV4_SYMBOL,
    TCP_CONNECT_IPV6_SYMBOL, TCP_CONNECT_SYMBOL, TCP_ENDPOINT_PART_SYMBOL, TCP_LISTEN_IPV4_SYMBOL,
    TCP_LISTEN_IPV6_SYMBOL, TCP_LISTEN_SYMBOL, TCP_LOCAL_PORT_SYMBOL, TCP_NO_DELAY_SYMBOL,
    TCP_RECEIVE_BUFFER_SYMBOL, TCP_RECEIVE_BUFFER_UNTIL_SYMBOL, TCP_RECEIVE_BYTES_SYMBOL,
    TCP_RECEIVE_SYMBOL, TCP_SEND_BYTES_SYMBOL, TCP_SEND_BYTES_UNTIL_SYMBOL, TCP_SEND_SYMBOL,
    TCP_SET_NO_DELAY_SYMBOL, TCP_SET_TTL_SYMBOL, TCP_SHUTDOWN_SYMBOL, TCP_TTL_SYMBOL,
    TEXT_VIEW_GET_RUNE_SYMBOL, UDP_BIND_IPV4_SYMBOL, UDP_BIND_IPV6_SYMBOL, UDP_BIND_SYMBOL,
    UDP_BROADCAST_SYMBOL, UDP_CLOSE_SYMBOL, UDP_ENDPOINT_PART_SYMBOL,
    UDP_JOIN_MULTICAST_IPV4_SYMBOL, UDP_LEAVE_MULTICAST_IPV4_SYMBOL, UDP_LOCAL_PORT_SYMBOL,
    UDP_RECEIVE_BUFFER_SYMBOL, UDP_RECEIVE_BUFFER_UNTIL_SYMBOL, UDP_RECEIVE_BYTES_SYMBOL,
    UDP_RECEIVE_SYMBOL, UDP_SEND_BYTES_TO_SYMBOL, UDP_SEND_BYTES_TO_UNTIL_SYMBOL,
    UDP_SEND_TO_SYMBOL, UDP_SET_BROADCAST_SYMBOL, UDP_SET_TTL_SYMBOL, UDP_TTL_SYMBOL,
    UNIX_ACCEPT_SYMBOL, UNIX_CLOSE_SYMBOL, UNIX_CONNECT_SYMBOL, UNIX_LISTEN_SYMBOL,
    UNIX_RECEIVE_BUFFER_SYMBOL, UNIX_RECEIVE_BUFFER_UNTIL_SYMBOL, UNIX_SEND_BYTES_SYMBOL,
    UNIX_SEND_BYTES_UNTIL_SYMBOL, UNIX_SHUTDOWN_SYMBOL, symbol,
};
pub use version::{
    ABI_SUPPORT_SYMBOL, ActorLifecycleStatus, ActorReceiveStatus, ActorSendStatus,
    AllocationSiteDescriptorAbi, ChannelReceiveStatus, ChannelSendStatus, CodecEventStatus,
    CodecEventTag, CodecReadEventAbi, CodecWriteEventAbi, GC_SAFE_POINT_V2_SYMBOL, INVALID_HANDLE,
    IterationCollectionKind, IterationStatus, NATIVE_ABI_1_VERSION, NATIVE_ABI_2_VERSION,
    NativeAbiVersion, NativeTaskStatus, SocketIoStatus, StringFormatTag, TextViewGetRuneAbi,
};
